[build]
  base = "."
  command = "npm install && cd server && npm install && cd ../client && npm install && npm run build"
  publish = "client/dist"

[functions]
  directory = "netlify/functions"
  node_bundler = "nft"
  included_files = ["server/**"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200